AWSTemplateFormatVersion: 2010-09-09
Description: Create S3 bucket with basic security policy and logging

### 07 Sep 2017  EdH  Generalized
### 20 Jul 2017  pete.gervais Fine Tuned bucket policy, outputs, logging
##############################################################################
Parameters:
  bucketname: 
    Description: 'Bucket name for new S3 bucket'
    Type: String
    Default: a-valid-dns-name
    AllowedPattern: '^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$'
    ConstraintDescription: 'Name MUST be 3 to 63 lower case, numbers or dashes'

##############################################################################
Mappings:
  my:      ### TODO: Change the settings in this map 
    map:
      ########################################################################
      tagADGroup:                  'F-TS-Server-Cloud'                             ## M2 - used by IAM Policies
      tagAPM:                      '20354'                            ## M1 - From ServiceNow - See https://wiki.cardinalhealth.net/AWS_Tags
      tagApplication:              'Patching'                             ## M1 - Do not use spaces!!!
      tagApplicationGroup:         'Cloud Engineering'                             ## M1 - AWS Console IAM role name
      tagAssignmentGroup:          'EITSS-Cloud-Engineering'                             ## M  - From ServiceNow APM record - See https://wiki.cardinalhealth.net/AWS_Tags
      tagCostCenter:               '1120000160'                       ## M1 - bucket may be deleted if invalid !!!!
      tagDataClass:                'InternalUseOnly'                  ## M1 - Public, InternalUseOnly, CAHPublic, CAHConfidential, CAHPrivate
      tagEnvironment:              'Dev'                              ## M1 - POC, Dev, Stage, Prod, QA, PreProd, Training, Tek
      tagRegulatory:               'null'                                 ## M2 - Typically null - See https://wiki.cardinalhealth.net/AWS_Tags
      tagRecoveryTier:             'Tier5'                            ## O  - (worst) Tier5, Tier4, Tier3, Tier2, Tier1      (best RTO/RPO = 24/4)
      tagServiceClass:             'Class1'                           ## O  - (worst) Class1, Class2, Class3, Class4, Class5 (best Mission Critical)
      tagTechnicalContact:         'raghurohit@cardinalhealth@cardinalhealth.com'         ## R  - their.name@cardinalhealth.com
      tagWhoBuilt:                 'raghurohit@cardinalhealth.com'         ## R  - your.name@cardinalhealth.com
  
### ### ###
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: {default: '!!! You MUST edit the template to set the map values !!!'}
        Parameters: [ bucketname ]
      - Label: {default: '!!! You MUST edit the template to set the map values !!!'}     
      - Label: {default: '>>>>>>> Do not proceed unless you have done so. <<<<<<<'}     

##############################################################################
Conditions:
  Regulated: !Not
    - !Equals [{'Fn::FindInMap': ['my','map','tagRegulatory']}, '']
##############################################################################
### All S3 features available at time of creation are included.
### Changes are commented out if not in use.
### If you need a feature, remove the comment # and fill out the parts you need.
Resources:
  s3bucket:
    Type: 'AWS::S3::Bucket'
    Properties: 
     #AccessControl: <AuthenticatedRead | AwsExecRead | BucketOwnerRead | BucketOwnerFullControl | LogDeliveryWrite | Private | PublicRead | PublicReadWrite>
      BucketName: !Ref bucketname
     #CorsConfiguration: <Rules that define cross-origin resource sharing of objects in this bucket>
     #  CORS Configuration
     #LifecycleConfiguration: <Rules that define how Amazon S3 manages objects during their lifetime>
     #  <Lifecycle Configuration>
      LoggingConfiguration:
        DestinationBucketName: !Sub 'aws-s3-logging-${AWS::Region}-${AWS::AccountId}'
        LogFilePrefix: !Ref bucketname
     #NotificationConfiguration: <onfiguration that defines how Amazon S3 handles bucket notifications>
     #  Notification Configuration
     #ReplicationConfiguration: <Configuration for replicating objects in an S3 bucket>
     #  Replication Configuration
     #VersioningConfiguration:
     #  Versioning Configuration
     #WebsiteConfiguration:
     #  Website Configuration Type
      Tags:
        - {Key: Name,             Value: {Ref: bucketname}}
        - {Key: ADGroup,          Value: {'Fn::FindInMap': ['my','map','tagADGroup']}}
        - {Key: APM,              Value: {'Fn::FindInMap': ['my','map','tagAPM']}}
        - {Key: Application,      Value: {'Fn::FindInMap': ['my','map','tagApplication']}}
        - {Key: ApplicationGroup, Value: {'Fn::FindInMap': ['my','map','tagApplicationGroup']}}
        - {Key: AssignmentGroup,  Value: {'Fn::FindInMap': ['my','map','tagAssignmentGroup']}}
        - {Key: CostCenter,       Value: {'Fn::FindInMap': ['my','map','tagCostCenter']}}
        - {Key: DataClass,        Value: {'Fn::FindInMap': ['my','map','tagDataClass']}}
        - {Key: Environment,      Value: {'Fn::FindInMap': ['my','map','tagEnvironment']}}
        - !If [Regulated, {Key: Regulatory, Value: {'Fn::FindInMap': ['my','map','tagRegulatory']}}, {Ref: 'AWS::NoValue'}]
        - {Key: TechnicalContact, Value: {'Fn::FindInMap': ['my','map','tagTechnicalContact']}}      
        - {Key: WhoBuilt,         Value: {'Fn::FindInMap': ['my','map','tagWhoBuilt']}}
  
          
          

          


Outputs:
  s3Bucketname:
    Description: Name of S3 bucket created
    Value: !Ref s3bucket
  s3BucketARN:
    Description: ARN of S3 bucket created
    Value: !GetAtt s3bucket.Arn
  